version: '3'

services:
  redis:
      image: "redis:alpine"
      ports:
        - "6379:6379"
      expose:
        - 6379
      restart:
        always
      networks:
        - redis

  app:
    build: ./
    volumes:
      - ./:/var/www/app
    ports:
      - 3000:3000
    networks:
    - redis
    environment:
      - REDIS_URL=redis://cache
      - NODE_ENV=development
      - PORT=3000
    command:
      sh -c 'npm i && npm run dev'

networks:
  redis:
    driver: bridge